### ISSUE TITLE
Final steps for ZIO 1.0 release

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1112]
Here is a list of important and potentially breaking changes I'd like to get in before 1.0:

 - [ ] `ZRef`, a more polymorphic version of `Ref` #913
 - [ ] Generalize errors on ZStream #634
 - [ ] Companion objects for effect aliases #744
 - [ ] Supervision overhaul #1081
 - [ ] Suspend overhaul #891
 - [ ] Companion objects for other type aliases #1111 
 - [ ] Scala 2.13 #1007 
 - [ ] Scala.js #803 

Nearly all other changes can be done in a source and binary-compatible way.

Anyone have anything else?

**Comment by kaishh** [comment]
I have

> Add `fiberId` of interrupting Fiber in `interrupted` instead of `Boolean`

on my list

**Comment by jdegoes** [comment]
@kaishh That may change with my work on supervision...

Btw are you OK with deleting `FiberLocal` for 1.0 in favor of `FiberRef`?

**Comment by kaishh** [comment]
@jdegoes
Well, a supervision kill may list the direct parent. To explain the motivation, knowing killer's fiberId in Cause is actually pretty important for http4s - we get a lot of interrupts in log and it's not clear if those are benign timeouts or something else...

Yeah, I'm good with FiberRefs.

**Comment by jdegoes** [comment]
@kaishh All right, let me do this as part of #1081

**Comment by kaishh** [comment]
@jdegoes Thank you very much!!

**Comment by NeQuissimus** [comment]
We'll create a ZIO based tets framework as a separate module post-1.0?!

**Comment by jdegoes** [comment]
Yes, and port all the tests over then!

**Comment by iravid** [comment]
I added #538 to the list.

**Comment by jdegoes** [comment]
Added #1325

**Comment by ghostdogpr** [comment]
With #634 done, we're getting close! 💪

**Comment by jdegoes** [comment]
I think we should plan to do 1.0 release on the ZIO Hackathon in Warsaw. It will require some work but we are quite close and the hackathon can provide some added human-power to close out any remaining issues...

**Comment by vasilmkd** [comment]
The code for #538 is done.

**Comment by jdegoes** [comment]
Update on ZIO 1.0:

There are two blockers currently. I'm working on both of them, about 20 hours a week. They are as follows:

1. **Jitter problem**. The "jitter problem" pertains to Schedule#jittered but is much larger in scope, and stems from the fact that it's not possible to write generic code that makes modifications to the environment. The ZIO#provideSome requires the shape be known statically. A variety of solutions have been proposed and / or prototyped by @adamfraser and @ioleo, together with ZIO Macros, developed by @mschuwalow, @ioleo, and others. The options are: bake-in ZIO macros in a way that still cross-compiles with Scala 3; use a lens encoding for environment; modify built-in environments to support decoration (just fixes jitter and friends, not the larger problem); and switch to a "set encoding" for services. I have a full prototype of the latter solution, developed with help from @mschuwalow , @ioleo , and @wi101, with troubleshooting help from @adamgfraser. To say it's _extremely promising_ would be an understatement. But the approach is not without tradeoffs  and some tests are failing and one issue remains to be solved. Volunteers welcome!
2. **Runtime system issues**. There are two separate issues in the runtime that need attention: auto-supervision and forced interruption (principally race-related). _Auto-supervision_: captures the full fiber graph now, and it does so without weak references. In practice, lots of production code appears to rely on the garbage collection of non-terminating fibers. The solution to this problem is to use weak sets to keep track of the fiber graph. Doing this in a way that allows race-free relocation of children of dead fibers is challenging. I have a POC but am still working through failing test cases. _Forced-interruption_: This issue is that racing two fibers leads to forced interruption of the loser, which manifests itself in surprising ways when finalizers are involved. The broader issue is the strength of forced interruption. I've been working on a design that will be less surprising, without sacrificing the expressive power of the current model. It's not a ton of work, nearly all the pieces are in place, I just need the time to make it happen.

Separately, we have various cleanup PRs in various stages that should be pushed on through before 1.0's backward compatibility guarantee will prevent them from being merged. These include by-name parameters, `ZRef`, and miscellaneous other changes.

I am not sure timeframe but I feel that this month is realistic. I also think that it will be wise to mark certain components of ZIO as being experimental, and not provide a guarantee of backward compatibility. These components include:

 - ZIO Streams (Sink needs some love and error handling is just being fleshed out)
 - ZManaged (the free encoding may change things, it is hard to say)
 - ZIO Test (seems relatively stable but @adamgfraser and I worked on a few uniformity improvements; and we don't really have any diffing capability right now)

So I'd recommend that we release 1.0 without a guarantee of backward compatibility for the above components, aiming to finalize them around 1.1. This way the broader ecosystem can rely on the core components, which have proven very stable, even while we refine and solidify the newer additions.

**Comment by jdegoes** [comment]
^^^ Cross-posted from Discord

**Comment by jdegoes** [comment]
Closing since everything here is done except for ZRef, which won't hold up the release.
