### ISSUE TITLE
Lower-level, more expressive foundation for ZStream

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#1388]
Lower-level foundation of Streams, which is stack-safe, does not require `Queue` for most combinators, and is readily understood as a "scoped" Java-style `InputStream`, without the unnecessary open / close operations.

It is trivially possible to implement `fold` in terms of `inputStream`; implementing `inputStream` in terms of `fold` would require a `Queue` (which is expected).

```scala
// An read on an input stream terminates normally because it is done (`None`) 
// or abnormally for some reason `Some(e: E)`:
type InputStream[+E, +A] = IO[Option[E], A]

trait ZStream[-R, +E, +A] {
  /**
   * Call `process` to obtain a managed input stream that can be used to read from 
   * the stream until it is empty (or possibly forever, if the stream is infinite). The 
   * provided `InputStream` is valid only inside the scope of the managed resource.
   */
  def inputStream: ZManaged[R, E, InputStream[E, A]]
}
```

Some interesting properties:

 - The failed read of an individual `A` can be retried (or ignored, or provided a fallback), independently of retrying or ignoring or providing a fallback for the whole stream
 - There is no need for a separate type parameter for client errors, because client errors occur only in consumption, and can be introduced on `run`, `fold`, `foreach`, etc., in which case supertype or manual unification could be used
 - Most operators are extremely trivial, and, indeed, the "guts" are simple enough for users to use:

```scala
stream1.zipWith(stream2) {
  case (inputStream1, inputStream2) =>
    ...
}
```

The only drawback I can see is that fusion is significantly harder to achieve; but indeed, there could exist two types of streams (subtypes of a sealed `ZStream`), one with `InputStream` as defined above, and one with `InputStream` as defined by `() => A` (very low level, not visible externally), which would throw both errors and end-of-stream; and this alternate constructor could perform extremely well for pure streams and synchronous effectful streams (async streams pretty much require the power of `ZIO` and will only be performant with `Chunk`).

/cc @iravid

**Comment by jdegoes** [comment]
Oh, and obviously `uncons` is extremely simple; and fixed or varying headers can be pulled off and leave a stream remainder, which was previously insanely difficult (`peel`) and not performant.

**Comment by iravid** [comment]
I like this! It's just an effectful iterator (e.g. `InputStream` is `next`) that establishes a scope.

I wonder if an equivalent to `hasNext` is needed?

**Comment by jdegoes** [comment]
`hasNext` could be useful but in most cases it would involve an effect and caching the read value (e.g. `Socket`); but you can already do that with the current representation, that is, you can read a value, and if you didn't like it, or want to "push" it back, you can put it into a stream and concat it onto the remainder.

**Comment by iravid** [comment]
Makes sense. Well, this is all very cool. I bet it is going to be vastly more performant than the current representation.

@mschuwalow Since you're already pulling stream apart for the errors - would you like to tackle this? :-)

**Comment by jdegoes** [comment]
>  I bet it is going to be vastly more performant than the current representation.

Certainly if one of the two subtypes of `ZStream` exposes an input stream that is just `() => A` (`next`), then it may even be possible to use `ZStream` in place of Scala collections (i.e. comparable performance for pure streams).

The performance of the concurrent combinators could go up 10x or more, probably, especially the insanely complex ones.

**Comment by jdegoes** [comment]
@iravid It also occurs to me that `ZSink` may be able to have a different representation, something like: `InputStream[E, A] => ZIO[R, E, (A0, B)]`. 

This alone could have massive performance ramifications on sink and sink composition. It's also easy to trampoline, too, compared to the current encoding.

**Comment by vasilmkd** [comment]
Would love to help out with this. Does this mean that I should drop my work on removing the `Step` from the current implementation of `ZSink`?

**Comment by mschuwalow** [comment]
This looks very cool. I would like to work on this, but I think after my current PRs are through I'll be busy for a bit. Still very excited to see how the next generation of ZStream will look like!

**Comment by iravid** [comment]
Ok, thanks @mschuwalow, looks like @vasilmkd will pick this up :-)

@vasilmkd - I think we should do this in several phases:
1. Introduce the `process: ZManaged[InputStream]` method and implement `fold` in terms of it
2. Start simplifying the big combinators and rewrite them in terms of `process`
3. Deal with Sink.

**Comment by iravid** [comment]
So yes, we should put the stepless sink on hold.

**Comment by mschuwalow** [comment]
@jdegoes @iravid 

> The only drawback I can see is that fusion is significantly harder to achieve; but indeed, there could exist two types of streams (subtypes of a sealed ZStream), one with InputStream as defined above, and one with InputStream as defined by () => A (very low level, not visible externally), which would throw both errors and end-of-stream; and this alternate constructor could perform extremely well for pure streams and synchronous effectful streams (async streams pretty much require the power of ZIO and will only be performant with Chunk).

How exactly would the second stream () => A work? Do you mean actually throwing in case of end of stream and error?

**Comment by iravid** [comment]
Yeah. A magic exception, and then you don't need to pay the cost of allocating an `Option` on each pull.

**Comment by iravid** [comment]
Actually alternatively that could also be a `null`.

**Comment by mschuwalow** [comment]
In that case maybe () => A | null may make more sense

**Comment by iravid** [comment]
jynx :-)

**Comment by vasilmkd** [comment]
> Ok, thanks @mschuwalow, looks like @vasilmkd will pick this up :-)
> 
> @vasilmkd - I think we should do this in several phases:
> 
>     1. Introduce the `process: ZManaged[InputStream]` method and implement `fold` in terms of it
> 
>     2. Start simplifying the big combinators and rewrite them in terms of `process`
> 
>     3. Deal with Sink.

Agree that there are several phases to this. That's why I said I'd like to help out. @mschuwalow can lead, I don't know the time sensitivity of this.

**Comment by mschuwalow** [comment]
:D
But should such streams be allowed to fail at all? Maybe start of as a PureStream
A => () | null while it executes no effects and switch to a ZStream IO[Option[E], A] once it begins doing effects

**Comment by mschuwalow** [comment]
> Agree that there are several phases to this. That's why I said I'd like to help out. @mschuwalow can lead, I don't know the time sensitivity of this.

Nah, I'm still very much a noob. Just get started on this and I'll maybe pick up a few tickets once I have time :D

**Comment by mschuwalow** [comment]
Never mind about our idea with null. This would break for primitives, or at least requires more thought

**Comment by iravid** [comment]
Good point. Although I think they'd box anyway when passing through a `scala.Function0`.

**Comment by jdegoes** [comment]
> Actually alternatively that could also be a null.

Can be `null` but that forces `AnyRef` which requires boxing on `A` (`Function0` is specialized, isn't it?).

Btw should we merge existing improvements or skip ahead to this??? /cc @mschuwalow @vasilmkd @iravid

**Comment by jdegoes** [comment]
> But should such streams be allowed to fail at all? Maybe start of as a PureStream

Users will never see this so it doesn't really matter. Also you have to "fail" to signal the end of the stream, so it's not really optional (though you could limit failure).

**Comment by iravid** [comment]
> Can be null but that forces AnyRef which requires boxing on A (Function0 is specialized, isn't it?).

When we worked on the specialization stuff for Chunk last year, I think we saw that although Function0 and Function1 are specialized, the compiler was not picking the specialized versions. At least in functions like `map` on Chunk.

> Btw should we merge existing improvements or skip ahead to this??? /cc @mschuwalow @vasilmkd @iravid

We'll hold them for a few days in which @vasilmkd will get the first phase of this refactor in. I'll add an implementation plan to this issue's description tonight :-)

**Comment by iravid** [comment]
## Implementation plan

### First pass (should be done in a single PR)
- [ ] Add the following type alias to `ZStream` (does this need an `R`?):
```scala
type InputStream[+E, +A] = IO[Option[E], A]
```
- [ ] Add the following abstract method to `ZStream`:
```scala
def process: ZManaged[R, E, InputStream[E, A]]
```
- [ ] Add a default implementation, `processDefault`, that uses `fold` to implement `process` using a queue. This way we don't have to migrate all combinators at once.
- [ ] Add `process = processDefault` to all the existing combinators and constructors. We should definitely not do a release before we get rid of this on most combinators.

@vasilmkd - would you like to take this?

### Second pass:
- [ ] Start moving all the combinators and constructors to use `process` directly. The implementation of `process` should live alongside `fold`, until we forward `fold` to `process`.

### Third pass:
- [ ] Forward `fold` to `process` on `ZStream`
- [ ] Get rid of the `fold` overrides on all the combinators/constructors

**Comment by vasilmkd** [comment]
Starting work on the first pass.

**Comment by mschuwalow** [comment]
> > But should such streams be allowed to fail at all? Maybe start of as a PureStream
> 
> Users will never see this so it doesn't really matter. Also you have to "fail" to signal the end of the stream, so it's not really optional (though you could limit failure).

That was more related to using null. I don't think it's relevant if we are throwing anyway.
The standard libary is also using exceptions for control flow so we are good to go :grin: 
https://github.com/scala/scala/blob/2.13.x/src/library/scala/util/control/ControlThrowable.scala

**Comment by vasilmkd** [comment]
Working on the second pass.

**Comment by vasilmkd** [comment]
Stream constructors (excluding ones going through `StreamPure`) have been converted. Work being done on migrating the combinators.

**Comment by iravid** [comment]
@jdegoes Now that we've written some combinators and constructors with this encoding, it's clear that the `InputStream` has to keep some internal state. When done naively as we've done so far, it's easy to for interruption on a pull to become unsafe.

For example:
```scala
  final def fromChunk[@specialized A](c: Chunk[A]): Stream[Nothing, A] =
    new Stream[Nothing, A] {
      override def process: Managed[Nothing, InputStream[Any, Nothing, A]] =
        for {
          index <- Ref.make(0).toManaged_
          len   = c.length
        } yield index.get.flatMap { i =>
          if (i >= len) InputStream.end
          else index.set(i + 1) *> InputStream.emit(c(i))
        }
    }
```

If the pull is interrupted between `index.set(i + 1)` and `emit`, we lose an element. We could switch them around (`emit <* set(i + 1)`) but then we risk duplicates on interruption. Or we could make this uninterruptible.

Sprinkling `uninterruptible` seems the right way to go, but we probably need some helpers on `InputStream` for safely constructing such regions. Any ideas on patterns that could help here?

**Comment by jdegoes** [comment]
@iravid I am still thinking about this. Essentially we have all the problems of "safe handoff".

Interrupting things can result in losses "at the edges" (queues, elements, transactions, etc.).

**Comment by jdegoes** [comment]
@iravid I am still thinking about this. Essentially we have all the problems of "safe handoff".

Interrupting things can result in losses "at the edges" (queues, elements, transactions, etc.).

**Comment by iravid** [comment]
Yes, that's a good summary of the issue. I mostly came to terms with it; not sure it's worth solving for now.

**Comment by mschuwalow** [comment]
At least in my opinion we have pretty much build an effectful iterator, which might not be the optimal base for some algorithms.

I have played around in a branch with having a "cached" stream (basically same semantics as scala stream / lazylist)
https://github.com/mschuwalow/scalaz-zio/blob/streamlist-experiments-2/streams/shared/src/main/scala/zio/stream/StreamList.scala
which can easily be constructed from a stream and also converted back to a stream an infinite number of times.
https://github.com/mschuwalow/scalaz-zio/blob/streamlist-experiments-2/streams/shared/src/main/scala/zio/stream/ZStream.scala#L1988

Maybe it is useful to have something like this. Parallel combinators can then be implented with "cursors" on the stream and the handoff problem disappears. On the other hand you'll definitely get a performance penalty for it.
 
My implementation is also currently not allowing the gc to collect irrelevant portions of the stream, but it might still be interesting for trying it out

**Comment by iravid** [comment]
So that's in fact a reified `unfoldM`, right @mschuwalow? Is that really different than a `ZStream` that caches elements it pulls as it goes?

**Comment by mschuwalow** [comment]
no that's exactly what it is.
my point was just that it is probably useful to have and i don't think we have anything like that currently.
