### ISSUE TITLE
ZIO Test: Prepare for 1.0 Release

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#1972]
Issue to track items needed before ZIO Test 1.0 release. Please feel free to add or provide feedback.

- [x]  support test annotations (#1951)
- [x] simplify backend types (#1971)
- [ ] make sure everything that can be private is
- [ ] benchmark property based testing or get confident we can make any necessary changes in a binary compatible way
- [x] determine what if anything we want to do to make it easier to compose `assertM` (#1888)
- [x] refactor `failureDetails` to be a nonempty list (#1333)
- [ ] any further improvements we need to make now to facilitate detailed result reporting
- [X] fix type inference issues with test aspects (#1991)
- [x] Add UManaged alias (#1999)
- [x] include mock improvements (#2000)

**Comment by ioleo** [comment]
For the Mocking framework:
[ ] add UManaged alias #1999

**Comment by regiskuckaertz** [comment]
hiya, I'd like to add

- [ ] no "Coming soon" page on the site. For a library of ZIO's stature, it has received a bit of criticism on this side of the ocean.

**Comment by adamgfraser** [comment]
Yes, I think this actually fits into a broader issue of needing to get ZIO Test its own microsite or at least section on the main navigation. Content for ZIO Test currently exists under "Use Cases - Testing" and "How To - Test Effects" but it is split across two places and the summary of the "How To" page says "coming soon" even though there is content on the subpages you can navigate to form the left hand side, which is confusing. I am going to spend more time on this once I get through some of the issues with the new environment encoding.

**Comment by regiskuckaertz** [comment]
Ouch, I missed the "Test" in the title, sorry for the confusion. I meant for the whole ZIO library, but yeah I agree with you the situation right now is not ideal. Let me know if I can help 👍

**Comment by jdegoes** [comment]
@adamgfraser I tried to update this as best as I could. Looks like we're getting close.

I might add some wish list things:

 - Environment narrowing for specs, so you could do: `spec @@ provideLayer(foo)`
 - Easy way to run tests that have some tag, e.g. `-- -tag "interruption"`.
 - Printing of random seeds from failed tests

I think Gen performance will improve but only with general Stream improvements. We probably don't need to worry about that in the ZIO Test layer.

**Comment by adamgfraser** [comment]
@jdegoes I think that is a good list. Regarding your specific points:

- Environment narrowing - Agreed. We need to think more about how to do that.
- Tags - That functionality already exists with the syntax you describe.
- Printing of random seeds - Yes. I will add that.

I think the other big thing to think about fitting in is the structured reporting of test results and metrics. I think we could probably do it in a binary compatible way but would be great to make some progress on that before 1.0. I think that could really be a differentiating feature for us.

**Comment by ioleo** [comment]
Some of work still to do:
- [ ] composable & more expressive mocks (and, or, andThen, repeats) + mocking composed environments #3000
- [ ] update mocking docs/examples
- [ ] move `zio-macros` project as submodule withing `zio/zio`
- [ ] drop `delegate/enrich` family of macros
- [ ] adjust accessors generation macro (`@accessible`) to use `Has`
- [ ] move method tags generation macro (`@mockable`) into ZIO Test

**Comment by ioleo** [comment]
A few more things I'll try to get in before 1.0 release:
- [ ] split macros into `zio-macros-core` & `zio-macros-test` (iff @adamgfraser confirms he's OK with that solution) & make sure they are ready to be published together with `zio/zio`
- [ ] mocking polymorphic methods #2978
- [ ] mock expecting no calls #3115
- [ ] reintroduce spies with implicit free encoding #3097
- [ ] support mocking ZStream methods #2734

**Comment by kitlangton** [comment]
I think we did this 🥳
