### ISSUE TITLE
ZIO 1.0 Discussion

### ISSUE THREAD

**Issue by jdegoes** [zio/zio#401]
List of things we need to wrap up to get to ZIO 1.0:

 - [x] Improve Scaladoc #413 
 - [x] Improve Microsite #417 
 - [x] Cats-Effect 1.0 instances for `Concurrent` and `ConcurrentEffect` #79 
 - [x] Finalization of data type and method names #287 
 - [x] Finish cleaning up API #507
 - [x] Breakup `interop` into distinct modules #394 #408 
 - [x] Composable / non-monolithic RTS #36 
 - [x] Solution for blocking IO #297 #248 ???
 - [x] Locking IO to thread pool  #297 #248 ???
 - [x] Built-in support for testing IO programs #510
 - [x] Scala.js support #22 #318 
 - [ ] Auditing of RTS for correctness #418 
 - [x] Improve package organization ???
 - [x] Migrate from extension methods to implicit ev: A =:= B #489

We're making good progress. With a little luck, I expect we can get to 1.0 by sometime in ~~January~~ ~~end of March~~ the beginning of June. 🎉

**Comment by hepin1989** [comment]
At least,the doc of Monix is very great,we should achive that.

**Comment by hepin1989** [comment]
Plus update dependencies, maybe with the help of scala-steward?

**Comment by hepin1989** [comment]
cross build with `scala 2.13`

**Comment by mijicd** [comment]
More on organizational side, it would be helpful to close the issues that are no longer relevant and assign the remaining ones to proper milestones.

**Comment by hepin1989** [comment]
refs:https://github.com/scalaz/scalaz-zio/pull/408

**Comment by hepin1989** [comment]
Cats-effect 1.1.0 is released.

**Comment by jdegoes** [comment]
@mijicd Working on it...and getting close, I hope! 😉

**Comment by jdegoes** [comment]
Nearly there!

**Comment by jdegoes** [comment]
Closed in favor of #1112
