### ISSUE TITLE
ZIO 2.0

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio#5470]
Issue to track remaining work to prepare for final release of ZIO 2.0.

## Performance

- [ ] Optimize performance (@jdegoes and @adamgfraser)

## Ergonomics and Safety

- [x] Make all constructors lazy (@adamgfraser - #5266)
- [x] Remove remaining usages of `M` suffix

## Operations

- [x] Implement direct logging support (@jdegoes - #5308)
- [x] Replace warnings with logs (@adamgfraser - #5509)
- [x] Move ZIO ZMX into ZIO Core (@adamgfraser - #5498)
- [x] Integrate ZIO ZMX with runtime metrics (@jdegoes)
- [x] Finalize ZIO ZMX API (@adamgfraser - #5498)
- [x] Tracing (@adamgfraser - #5744)

## Streaming

- [x] Implement remaining operators in terms of channel encoding (@iravid - #4886)

## Testing

- [x] Implement shared layers across specs (@zagyi - #4827)

## Migration

- [x] Scalafix migration rule (@kitlangton - #5739)
- [x] Migration guide (@khajavi - #5381)
- [ ] Releases of ZIO ecosystem libraries
